### ISSUE TITLE
Need to Localizable

### ISSUE THREAD

**Issue by mjkim0727** [zayronxio/Plasma-Control-Hub#1]
This plasmoid is great.

So, Can you make localizable this plasmoid?

**Comment by zayronxio** [comment]
I have added installation method in the readme

**Comment by Vistaus** [comment]
But it's still not translatable. I would love to add the Dutch translation if this plasmoid can be made translatable.

**Comment by zayronxio** [comment]
I have added a new method to manage translations. It currently supports 20 different languages. The file is in the js folder and you can add your translations yourself if it is not available.

**Comment by Vistaus** [comment]
Thanks, I'm going to go ahead with the Dutch translation then! 🙂

**Comment by Vistaus** [comment]
Actually, the translation seems to be good already, so no work for me. 🙂
