### ISSUE TITLE
Plasma Control Hub doen't work

### ISSUE THREAD

**Issue by pnedyalkov91** [zayronxio/Plasma-Control-Hub#2]
I have got an error message when I try to load the widget:
file:///home/pnedyalkov/.local/share/plasma/plasmoids/Plasma.Control.Hub/contents/ui/main.qml:642:53: NightColorMonitor is not a type

I installed it using this procedure:
1. Right click on the desktop
2. Click on "Add Widgets"
3. Click on "Get New Widgets"
4. Click on "Download New Plasma Widgets"
5. Search for "Plasma Control Hub"
6. Click on "Install".

My system configuration:
Operating System: Arch Linux 
KDE Plasma Version: 6.0.90
KDE Frameworks Version: 6.2.0
Qt Version: 6.7.1
Kernel Version: 6.9.2-arch1-1 (64-bit)
Graphics Platform: Wayland

![image](https://github.com/zayronxio/Plasma-Control-Hub/assets/59796383/99bb69fc-caf1-4f2f-9e63-cf0178eaf605)

**Comment by henkiewie** [comment]
+1 KDE neon 6.1. Worked on 6.0 Part of sonoma dark/light global theme.

**Comment by benmordecai** [comment]
I have the identical error on Arch with X11

**Comment by benmordecai** [comment]
Note the similar Control Centre app has a similar bug and someone already found a solution: https://github.com/Prayag2/kde_controlcentre/issues/64

**Comment by zayronxio** [comment]
It has already been resolved try the latest version available in the kde store

**Comment by henkiewie** [comment]
Yep. Global thems still act a bit funny on KDE neon on my machine, but an uninstall, reboot and install of the sonoma dark and light seemed to do the trick. Thanks.
<img width="341" alt="Screenshot 2024-07-16 at 09 40 38" src="https://github.com/user-attachments/assets/d953ca48-e36d-431b-a256-80d19166370d">
