### ISSUE TITLE
Widget not loading

### ISSUE THREAD

**Issue by weits** [zayronxio/Plasma-Control-Hub#4]
Getting this error:
file:///home/weits/.local/share/plasma/plasmoids/com.github.boraerciyas.controlcentre/contents/ui/main.qml:67:25: Type FullRepresentation unavailable

file:///home/weits/.local/share/plasma/plasmoids/com.github.boraerciyas.controlcentre/contents/ui/FullRepresentation.qml:75:21: Type Components.RedShift unavailable

file:///home/weits/.local/share/plasma/plasmoids/com.github.boraerciyas.controlcentre/contents/ui/components/RedShift.qml:64:5: NightColorInhibitor is not a type

KDE Neon, Plasma 6.1.5, KF 6.6.0

**Comment by zayronxio** [comment]
I'm sorry but this is not the appropriate github repository to upload this issues, you are using a different plasmoid than plasma control hub
